### ISSUE TITLE
Task exception was never retrieved 

### ISSUE THREAD

**Issue by lethallynx** [ziv1234/hass_dynalite_component#2]
Error doing job: Task exception was never retrieved
8:47 PM /usr/src/homeassistant/homeassistant/core.py (ERROR) - message first occurred at 8:20 PM and shows up 303 times

Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/dynalite_lib/dynet.py", line 414, in _receive
    "{:02x}".format(ord(c)) for c in self._inBuffer[:8]
  File "/usr/local/lib/python3.7/site-packages/dynalite_lib/dynet.py", line 414, in <genexpr>
    "{:02x}".format(ord(c)) for c in self._inBuffer[:8]
TypeError: ord() expected string of length 1, but int found

**Comment by ziv1234** [comment]
Ok. Will look into it. Can you send me the log file? It could help

**Comment by ziv1234** [comment]
which version of the library dynalite_lib did it install? It should have been 0.1.28 which doesn't have this line of code

**Comment by ziv1234** [comment]
Ok. Found out that i added unit tests and actually discovered this, but forgot to push. Pushed now with the versions updated, so you can pull again.

Note that i never reached this error condition in my environment, so it could indicate that something else is problematic. Let me know what happens next.

**Comment by lethallynx** [comment]
Ok updated to the latest version.

Now i am getting the following:

`2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Dynet Sent: bytearray(b'\x1c\x03\x01a\x00\x00\xff\x80')
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:b1:b1:00:00:72:15:ac - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet b1:b1:00:00:72:15:ac:03 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet b1:00:00:72:15:ac:03:22 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:00:72:15:ac:03:22:dc - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:72:15:ac:03:22:dc:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 72:15:ac:03:22:dc:00:01 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 15:ac:03:22:dc:00:01:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet ac:03:22:dc:00:01:00:03 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 03:22:dc:00:01:00:03:ff - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 22:dc:00:01:00:03:ff:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet dc:00:01:00:03:ff:00:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:01:00:03:ff:00:00:02 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 01:00:03:ff:00:00:02:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:03:ff:00:00:02:00:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 03:ff:00:00:02:00:00:b9 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet ff:00:00:02:00:00:b9:b2 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:00:02:00:00:b9:b2:ac - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:02:00:00:b9:b2:ac:04 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 02:00:00:b9:b2:ac:04:23 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:00:b9:b2:ac:04:23:dc - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:b9:b2:ac:04:23:dc:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet b9:b2:ac:04:23:dc:00:01 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet b2:ac:04:23:dc:00:01:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet ac:04:23:dc:00:01:00:03 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 04:23:dc:00:01:00:03:ff - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 23:dc:00:01:00:03:ff:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet dc:00:01:00:03:ff:00:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:01:00:03:ff:00:00:02 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 01:00:03:ff:00:00:02:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:03:ff:00:00:02:00:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 03:ff:00:00:02:00:00:b1 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet ff:00:00:02:00:00:b1:b1 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:00:02:00:00:b1:b1:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:02:00:00:b1:b1:00:00 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 02:00:00:b1:b1:00:00:79 - moving one byte forward
2019-12-23 18:58:31 DEBUG (MainThread) [dynalite_lib.dynet] Unable to process packet 00:00:b1:b1:00:00:79:16 - moving one byte forward`

The light successfully turns on, but the status still doesn't get picked up obviously. 

Attached is my configuration.yaml (renamed to .txt for upload)
[configuration.txt](https://github.com/ziv1234/hass_dynalite_component/files/3994270/configuration.txt)

**Comment by lethallynx** [comment]
Ethernet Gateway info:
![image](https://user-images.githubusercontent.com/963869/71348130-91962300-25b7-11ea-99ad-27458d4aa147.png)

**Comment by lethallynx** [comment]
Home assistant info:
![image](https://user-images.githubusercontent.com/963869/71348175-b4283c00-25b7-11ea-9782-84c371cc35c9.png)

**Comment by ziv1234** [comment]
What type of dynalite gateway do you use? It is trying to pick up a dynalite command syntax that is 8 bytes that start with 0x1c (with checksum and stuff). However, it doesn’t see it in this sequence. Perhaps it is a different type of gateway? If you send me yours I can try and figure it out and fix

**Comment by ziv1234** [comment]
Is this the ethernet gateway or the dynalite gateway?

**Comment by lethallynx** [comment]
It is the PDEG
https://www.dynalite.org/lighting-controls/integration-devices/ethernet-gateway-10-100-baset-gateway

**Comment by ziv1234** [comment]
I use the Envision Gateway, but this also seems that it should work. Do you know what mode it is set for? Looks from some reading that it should be “passive TCP”, but there is not much documentation

**Comment by lethallynx** [comment]
What does the device status screen look like in yours? 

What version of firmware does it report?

**Comment by ziv1234** [comment]
[A screenshot of a cell phone  Description automatically generated]
